<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class BookingSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $bookings = [
            [
                'hall_id' => 1,
                'customer_id' => 1,
                'event_type' => 'حفل زفاف',
                'event_date' => '2024-01-15',
                'start_time' => '18:00:00',
                'end_time' => '23:00:00',
                'guests_count' => 300,
                'total_amount' => 15000,
                'deposit_amount' => 5000,
                'status' => 'confirmed',
                'payment_status' => 'paid',
                'notes' => 'تحتاج تزيين خاص',
            ],
            [
                'hall_id' => 2,
                'customer_id' => 2,
                'event_type' => 'مؤتمر تجاري',
                'event_date' => '2024-01-20',
                'start_time' => '09:00:00',
                'end_time' => '17:00:00',
                'guests_count' => 150,
                'total_amount' => 6000,
                'deposit_amount' => 2000,
                'status' => 'confirmed',
                'payment_status' => 'paid',
                'notes' => 'تحتاج شاشات عرض إضافية',
            ],
            [
                'hall_id' => 3,
                'customer_id' => 3,
                'event_type' => 'حفل تخرج',
                'event_date' => '2024-01-25',
                'start_time' => '19:00:00',
                'end_time' => '22:00:00',
                'guests_count' => 120,
                'total_amount' => 4500,
                'deposit_amount' => 1500,
                'status' => 'pending',
                'payment_status' => 'pending',
                'notes' => 'في انتظار تأكيد الدفع',
            ],
            [
                'hall_id' => 4,
                'customer_id' => 4,
                'event_type' => 'حفل خطوبة',
                'event_date' => '2024-02-01',
                'start_time' => '20:00:00',
                'end_time' => '00:00:00',
                'guests_count' => 250,
                'total_amount' => 9000,
                'deposit_amount' => 3000,
                'status' => 'confirmed',
                'payment_status' => 'paid',
                'notes' => '',
            ],
            [
                'hall_id' => 5,
                'customer_id' => 5,
                'event_type' => 'ورشة عمل',
                'event_date' => '2024-02-05',
                'start_time' => '10:00:00',
                'end_time' => '16:00:00',
                'guests_count' => 80,
                'total_amount' => 3500,
                'deposit_amount' => 1000,
                'status' => 'confirmed',
                'payment_status' => 'paid',
                'notes' => '',
            ],
            [
                'hall_id' => 6,
                'customer_id' => 6,
                'event_type' => 'حفل ميلاد',
                'event_date' => '2024-02-10',
                'start_time' => '18:00:00',
                'end_time' => '22:00:00',
                'guests_count' => 350,
                'total_amount' => 12000,
                'deposit_amount' => 4000,
                'status' => 'confirmed',
                'payment_status' => 'paid',
                'notes' => 'تحتاج كيك كبير',
            ],
            [
                'hall_id' => 7,
                'customer_id' => 7,
                'event_type' => 'اجتماع شركة',
                'event_date' => '2024-02-15',
                'start_time' => '14:00:00',
                'end_time' => '18:00:00',
                'guests_count' => 200,
                'total_amount' => 7000,
                'deposit_amount' => 2000,
                'status' => 'cancelled',
                'payment_status' => 'pending',
                'notes' => 'تم الإلغاء من العميل',
            ],
            [
                'hall_id' => 8,
                'customer_id' => 8,
                'event_type' => 'ندوة علمية',
                'event_date' => '2024-02-20',
                'start_time' => '16:00:00',
                'end_time' => '20:00:00',
                'guests_count' => 150,
                'total_amount' => 5500,
                'deposit_amount' => 1800,
                'status' => 'confirmed',
                'payment_status' => 'paid',
                'notes' => '',
            ],
            [
                'hall_id' => 9,
                'customer_id' => 9,
                'event_type' => 'حفل زفاف',
                'event_date' => '2024-02-25',
                'start_time' => '19:00:00',
                'end_time' => '01:00:00',
                'guests_count' => 500,
                'total_amount' => 18000,
                'deposit_amount' => 6000,
                'status' => 'confirmed',
                'payment_status' => 'paid',
                'notes' => 'تحتاج تزيين فاخر',
            ],
            [
                'hall_id' => 10,
                'customer_id' => 10,
                'event_type' => 'مؤتمر طبي',
                'event_date' => '2024-03-01',
                'start_time' => '08:00:00',
                'end_time' => '18:00:00',
                'guests_count' => 100,
                'total_amount' => 4000,
                'deposit_amount' => 1200,
                'status' => 'confirmed',
                'payment_status' => 'paid',
                'notes' => '',
            ],
            [
                'hall_id' => 11,
                'customer_id' => 11,
                'event_type' => 'حفل خطوبة',
                'event_date' => '2024-03-05',
                'start_time' => '20:00:00',
                'end_time' => '00:00:00',
                'guests_count' => 300,
                'total_amount' => 11000,
                'deposit_amount' => 3500,
                'status' => 'pending',
                'payment_status' => 'pending',
                'notes' => 'في انتظار تأكيد الدفع',
            ],
            [
                'hall_id' => 12,
                'customer_id' => 12,
                'event_type' => 'اجتماع مجلس إدارة',
                'event_date' => '2024-03-10',
                'start_time' => '15:00:00',
                'end_time' => '17:00:00',
                'guests_count' => 40,
                'total_amount' => 2000,
                'deposit_amount' => 500,
                'status' => 'confirmed',
                'payment_status' => 'paid',
                'notes' => '',
            ],
            [
                'hall_id' => 13,
                'customer_id' => 13,
                'event_type' => 'حفل تخرج',
                'event_date' => '2024-03-15',
                'start_time' => '18:00:00',
                'end_time' => '21:00:00',
                'guests_count' => 180,
                'total_amount' => 6000,
                'deposit_amount' => 2000,
                'status' => 'confirmed',
                'payment_status' => 'paid',
                'notes' => '',
            ],
            [
                'hall_id' => 14,
                'customer_id' => 14,
                'event_type' => 'مؤتمر تقني',
                'event_date' => '2024-03-20',
                'start_time' => '09:00:00',
                'end_time' => '17:00:00',
                'guests_count' => 700,
                'total_amount' => 22000,
                'deposit_amount' => 7000,
                'status' => 'confirmed',
                'payment_status' => 'paid',
                'notes' => 'تحتاج معدات تقنية متقدمة',
            ],
            [
                'hall_id' => 15,
                'customer_id' => 15,
                'event_type' => 'حفل ميلاد',
                'event_date' => '2024-03-25',
                'start_time' => '17:00:00',
                'end_time' => '20:00:00',
                'guests_count' => 70,
                'total_amount' => 3000,
                'deposit_amount' => 1000,
                'status' => 'confirmed',
                'payment_status' => 'paid',
                'notes' => '',
            ],
            [
                'hall_id' => 16,
                'customer_id' => 16,
                'event_type' => 'حفل زفاف',
                'event_date' => '2024-04-01',
                'start_time' => '19:00:00',
                'end_time' => '01:00:00',
                'guests_count' => 400,
                'total_amount' => 14000,
                'deposit_amount' => 4500,
                'status' => 'pending',
                'payment_status' => 'pending',
                'notes' => 'في انتظار تأكيد الدفع',
            ],
            [
                'hall_id' => 17,
                'customer_id' => 17,
                'event_type' => 'ندوة ثقافية',
                'event_date' => '2024-04-05',
                'start_time' => '19:00:00',
                'end_time' => '22:00:00',
                'guests_count' => 220,
                'total_amount' => 7500,
                'deposit_amount' => 2500,
                'status' => 'confirmed',
                'payment_status' => 'paid',
                'notes' => '',
            ],
            [
                'hall_id' => 18,
                'customer_id' => 18,
                'event_type' => 'اجتماع عمل',
                'event_date' => '2024-04-10',
                'start_time' => '13:00:00',
                'end_time' => '15:00:00',
                'guests_count' => 50,
                'total_amount' => 2500,
                'deposit_amount' => 800,
                'status' => 'confirmed',
                'payment_status' => 'paid',
                'notes' => '',
            ],
            [
                'hall_id' => 19,
                'customer_id' => 19,
                'event_type' => 'مؤتمر اقتصادي',
                'event_date' => '2024-04-15',
                'start_time' => '09:00:00',
                'end_time' => '17:00:00',
                'guests_count' => 650,
                'total_amount' => 20000,
                'deposit_amount' => 6000,
                'status' => 'confirmed',
                'payment_status' => 'paid',
                'notes' => 'تحتاج ترجمة فورية',
            ],
            [
                'hall_id' => 20,
                'customer_id' => 20,
                'event_type' => 'حفل خطوبة',
                'event_date' => '2024-04-20',
                'start_time' => '20:00:00',
                'end_time' => '00:00:00',
                'guests_count' => 280,
                'total_amount' => 9000,
                'deposit_amount' => 3000,
                'status' => 'confirmed',
                'payment_status' => 'paid',
                'notes' => '',
            ],
        ];

        foreach ($bookings as $booking) {
            DB::table('bookings')->insert(array_merge($booking, [
                'created_at' => now(),
                'updated_at' => now(),
            ]));
        }
    }
}
