<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class HallSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $halls = [
            [
                'name' => 'قاعة النجاح الكبرى',
                'description' => 'قاعة فاخرة للمناسبات الكبيرة',
                'capacity' => 500,
                'price_per_hour' => 2000,
                'price_per_day' => 15000,
                'address' => 'الرياض - شارع الملك فهد',
                'photos' => json_encode(['hall1.jpg', 'hall1_2.jpg']),
                'amenities' => json_encode(['مكيف', 'إنترنت', 'شاشات عرض', 'صوتيات']),
                'is_available' => 1,
            ],
            [
                'name' => 'قاعة الأصالة',
                'description' => 'قاعة أنيقة للاجتماعات والمناسبات',
                'capacity' => 200,
                'price_per_hour' => 800,
                'price_per_day' => 6000,
                'address' => 'جدة - شارع التحلية',
                'photos' => json_encode(['hall2.jpg', 'hall2_2.jpg']),
                'amenities' => json_encode(['مكيف', 'إنترنت', 'شاشة عرض']),
                'is_available' => 1,
            ],
            [
                'name' => 'قاعة الإبداع',
                'description' => 'قاعة حديثة للفعاليات الإبداعية',
                'capacity' => 150,
                'price_per_hour' => 600,
                'price_per_day' => 4500,
                'address' => 'الدمام - شارع الملك خالد',
                'photos' => json_encode(['hall3.jpg']),
                'amenities' => json_encode(['مكيف', 'إنترنت', 'إضاءة ذكية']),
                'is_available' => 0,
            ],
            [
                'name' => 'قاعة التميز',
                'description' => 'قاعة فاخرة للمناسبات الخاصة',
                'capacity' => 300,
                'price_per_hour' => 1200,
                'price_per_day' => 9000,
                'address' => 'مكة - شارع العزيزية',
                'photos' => json_encode(['hall4.jpg', 'hall4_2.jpg']),
                'amenities' => json_encode(['مكيف', 'إنترنت', 'شاشات عرض', 'صوتيات', 'إضاءة']),
                'is_available' => 1,
            ],
            [
                'name' => 'قاعة المستقبل',
                'description' => 'قاعة تقنية للفعاليات الحديثة',
                'capacity' => 100,
                'price_per_hour' => 500,
                'price_per_day' => 3500,
                'address' => 'المدينة - شارع الملك عبدالله',
                'photos' => json_encode(['hall5.jpg']),
                'amenities' => json_encode(['مكيف', 'إنترنت', 'شاشات LED']),
                'is_available' => 1,
            ],
            [
                'name' => 'قاعة الوفاء',
                'description' => 'قاعة كلاسيكية للمناسبات التقليدية',
                'capacity' => 400,
                'price_per_hour' => 1500,
                'price_per_day' => 12000,
                'address' => 'الرياض - شارع العليا',
                'photos' => json_encode(['hall6.jpg', 'hall6_2.jpg']),
                'amenities' => json_encode(['مكيف', 'إنترنت', 'شاشات عرض', 'صوتيات']),
                'is_available' => 1,
            ],
            [
                'name' => 'قاعة الإنجاز',
                'description' => 'قاعة متعددة الأغراض',
                'capacity' => 250,
                'price_per_hour' => 900,
                'price_per_day' => 7000,
                'address' => 'جدة - شارع فلسطين',
                'photos' => json_encode(['hall7.jpg']),
                'amenities' => json_encode(['مكيف', 'إنترنت', 'شاشة عرض']),
                'is_available' => 0,
            ],
            [
                'name' => 'قاعة الرؤية',
                'description' => 'قاعة عصرية للفعاليات التجارية',
                'capacity' => 180,
                'price_per_hour' => 700,
                'price_per_day' => 5500,
                'address' => 'الدمام - شارع الملك عبدالعزيز',
                'photos' => json_encode(['hall8.jpg']),
                'amenities' => json_encode(['مكيف', 'إنترنت', 'شاشات عرض']),
                'is_available' => 1,
            ],
            [
                'name' => 'قاعة الإحسان',
                'description' => 'قاعة فاخرة للمناسبات الكبيرة',
                'capacity' => 600,
                'price_per_hour' => 2500,
                'price_per_day' => 18000,
                'address' => 'مكة - شارع إبراهيم الخليل',
                'photos' => json_encode(['hall9.jpg', 'hall9_2.jpg']),
                'amenities' => json_encode(['مكيف', 'إنترنت', 'شاشات عرض', 'صوتيات', 'إضاءة']),
                'is_available' => 1,
            ],
            [
                'name' => 'قاعة التقدم',
                'description' => 'قاعة حديثة للفعاليات العلمية',
                'capacity' => 120,
                'price_per_hour' => 550,
                'price_per_day' => 4000,
                'address' => 'المدينة - شارع الملك فيصل',
                'photos' => json_encode(['hall10.jpg']),
                'amenities' => json_encode(['مكيف', 'إنترنت', 'شاشة عرض']),
                'is_available' => 1,
            ],
            [
                'name' => 'قاعة الريادة',
                'description' => 'قاعة فاخرة للمناسبات الرسمية',
                'capacity' => 350,
                'price_per_hour' => 1400,
                'price_per_day' => 11000,
                'address' => 'الرياض - شارع الملك عبدالله',
                'photos' => json_encode(['hall11.jpg', 'hall11_2.jpg']),
                'amenities' => json_encode(['مكيف', 'إنترنت', 'شاشات عرض', 'صوتيات']),
                'is_available' => 0,
            ],
            [
                'name' => 'قاعة الإبداع الصغيرة',
                'description' => 'قاعة صغيرة للاجتماعات',
                'capacity' => 50,
                'price_per_hour' => 300,
                'price_per_day' => 2000,
                'address' => 'جدة - شارع التحلية',
                'photos' => json_encode(['hall12.jpg']),
                'amenities' => json_encode(['مكيف', 'إنترنت']),
                'is_available' => 1,
            ],
            [
                'name' => 'قاعة النجاح المتوسطة',
                'description' => 'قاعة متوسطة للمناسبات العائلية',
                'capacity' => 200,
                'price_per_hour' => 800,
                'price_per_day' => 6000,
                'address' => 'الدمام - شارع الملك خالد',
                'photos' => json_encode(['hall13.jpg']),
                'amenities' => json_encode(['مكيف', 'إنترنت', 'شاشة عرض']),
                'is_available' => 1,
            ],
            [
                'name' => 'قاعة الأصالة الكبرى',
                'description' => 'قاعة كبيرة للمؤتمرات',
                'capacity' => 800,
                'price_per_hour' => 3000,
                'price_per_day' => 22000,
                'address' => 'مكة - شارع العزيزية',
                'photos' => json_encode(['hall14.jpg', 'hall14_2.jpg']),
                'amenities' => json_encode(['مكيف', 'إنترنت', 'شاشات عرض', 'صوتيات', 'إضاءة']),
                'is_available' => 1,
            ],
            [
                'name' => 'قاعة التميز الصغيرة',
                'description' => 'قاعة صغيرة للاجتماعات الخاصة',
                'capacity' => 80,
                'price_per_hour' => 400,
                'price_per_day' => 3000,
                'address' => 'المدينة - شارع الملك عبدالله',
                'photos' => json_encode(['hall15.jpg']),
                'amenities' => json_encode(['مكيف', 'إنترنت']),
                'is_available' => 1,
            ],
            [
                'name' => 'قاعة المستقبل الكبرى',
                'description' => 'قاعة تقنية كبيرة للفعاليات',
                'capacity' => 450,
                'price_per_hour' => 1800,
                'price_per_day' => 14000,
                'address' => 'الرياض - شارع الملك فهد',
                'photos' => json_encode(['hall16.jpg', 'hall16_2.jpg']),
                'amenities' => json_encode(['مكيف', 'إنترنت', 'شاشات LED', 'صوتيات']),
                'is_available' => 0,
            ],
            [
                'name' => 'قاعة الوفاء المتوسطة',
                'description' => 'قاعة متوسطة للمناسبات',
                'capacity' => 250,
                'price_per_hour' => 1000,
                'price_per_day' => 7500,
                'address' => 'جدة - شارع فلسطين',
                'photos' => json_encode(['hall17.jpg']),
                'amenities' => json_encode(['مكيف', 'إنترنت', 'شاشة عرض']),
                'is_available' => 1,
            ],
            [
                'name' => 'قاعة الإنجاز الصغيرة',
                'description' => 'قاعة صغيرة للاجتماعات',
                'capacity' => 60,
                'price_per_hour' => 350,
                'price_per_day' => 2500,
                'address' => 'الدمام - شارع الملك عبدالعزيز',
                'photos' => json_encode(['hall18.jpg']),
                'amenities' => json_encode(['مكيف', 'إنترنت']),
                'is_available' => 1,
            ],
            [
                'name' => 'قاعة الرؤية الكبرى',
                'description' => 'قاعة كبيرة للمؤتمرات التجارية',
                'capacity' => 700,
                'price_per_hour' => 2800,
                'price_per_day' => 20000,
                'address' => 'مكة - شارع إبراهيم الخليل',
                'photos' => json_encode(['hall19.jpg', 'hall19_2.jpg']),
                'amenities' => json_encode(['مكيف', 'إنترنت', 'شاشات عرض', 'صوتيات', 'إضاءة']),
                'is_available' => 1,
            ],
            [
                'name' => 'قاعة الإحسان المتوسطة',
                'description' => 'قاعة متوسطة للمناسبات',
                'capacity' => 300,
                'price_per_hour' => 1200,
                'price_per_day' => 9000,
                'address' => 'المدينة - شارع الملك فيصل',
                'photos' => json_encode(['hall20.jpg']),
                'amenities' => json_encode(['مكيف', 'إنترنت', 'شاشة عرض', 'صوتيات']),
                'is_available' => 1,
            ],
        ];

        foreach ($halls as $hall) {
            DB::table('halls')->insert(array_merge($hall, [
                'created_at' => now(),
                'updated_at' => now(),
            ]));
        }
    }
}
