<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class MembershipSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $memberships = [
            [
                'name' => 'العضوية البرونزية',
                'description' => 'عضوية أساسية للاستخدام المحدود',
                'price' => 500,
                'duration_days' => 30,
                'is_active' => 1,
                'benefits' => json_encode(['حجز قاعات', 'خدمات أساسية']),
                'max_halls' => 1,
                'max_bookings_per_month' => 5,
                'priority_support' => 0,
                'custom_branding' => 0,
                'advanced_analytics' => 0,
            ],
            [
                'name' => 'العضوية الفضية',
                'description' => 'عضوية متوسطة مع مزايا إضافية',
                'price' => 1000,
                'duration_days' => 30,
                'is_active' => 1,
                'benefits' => json_encode(['حجز قاعات', 'خدمات متقدمة', 'أولوية الحجز']),
                'max_halls' => 2,
                'max_bookings_per_month' => 10,
                'priority_support' => 1,
                'custom_branding' => 0,
                'advanced_analytics' => 0,
            ],
            [
                'name' => 'العضوية الذهبية',
                'description' => 'عضوية فاخرة مع جميع المزايا',
                'price' => 2000,
                'duration_days' => 30,
                'is_active' => 1,
                'benefits' => json_encode(['حجز قاعات', 'جميع الخدمات', 'أولوية قصوى']),
                'max_halls' => 5,
                'max_bookings_per_month' => 20,
                'priority_support' => 1,
                'custom_branding' => 1,
                'advanced_analytics' => 1,
            ],
            [
                'name' => 'العضوية البلاتينية',
                'description' => 'عضوية VIP حصرية',
                'price' => 5000,
                'duration_days' => 30,
                'is_active' => 1,
                'benefits' => json_encode(['حجز قاعات', 'خدمات VIP', 'خصم كبير']),
                'max_halls' => 10,
                'max_bookings_per_month' => 50,
                'priority_support' => 1,
                'custom_branding' => 1,
                'advanced_analytics' => 1,
            ],
            [
                'name' => 'العضوية السنوية البرونزية',
                'description' => 'عضوية سنوية أساسية',
                'price' => 5000,
                'duration_days' => 365,
                'is_active' => 1,
                'benefits' => json_encode(['حجز قاعات', 'خدمات أساسية']),
                'max_halls' => 1,
                'max_bookings_per_month' => 60,
                'priority_support' => 0,
                'custom_branding' => 0,
                'advanced_analytics' => 0,
            ],
            [
                'name' => 'العضوية السنوية الفضية',
                'description' => 'عضوية سنوية متوسطة',
                'price' => 10000,
                'duration_days' => 365,
                'is_active' => 1,
                'benefits' => json_encode(['حجز قاعات', 'خدمات متقدمة', 'أولوية الحجز']),
                'max_halls' => 3,
                'max_bookings_per_month' => 120,
                'priority_support' => 1,
                'custom_branding' => 0,
                'advanced_analytics' => 1,
            ],
            [
                'name' => 'العضوية السنوية الذهبية',
                'description' => 'عضوية سنوية فاخرة',
                'price' => 20000,
                'duration_days' => 365,
                'is_active' => 1,
                'benefits' => json_encode(['حجز قاعات', 'جميع الخدمات', 'أولوية قصوى']),
                'max_halls' => 10,
                'max_bookings_per_month' => 240,
                'priority_support' => 1,
                'custom_branding' => 1,
                'advanced_analytics' => 1,
            ],
            [
                'name' => 'العضوية السنوية البلاتينية',
                'description' => 'عضوية سنوية VIP حصرية',
                'price' => 50000,
                'duration_days' => 365,
                'is_active' => 1,
                'benefits' => json_encode(['حجز قاعات', 'خدمات VIP', 'خصم كبير']),
                'max_halls' => 50,
                'max_bookings_per_month' => 600,
                'priority_support' => 1,
                'custom_branding' => 1,
                'advanced_analytics' => 1,
            ],
            [
                'name' => 'العضوية الشهرية الأساسية',
                'description' => 'عضوية شهرية للاستخدام الأساسي',
                'price' => 200,
                'duration_days' => 30,
                'is_active' => 1,
                'benefits' => json_encode(['حجز قاعات', 'خدمات أساسية']),
                'max_halls' => 1,
                'max_bookings_per_month' => 3,
                'priority_support' => 0,
                'custom_branding' => 0,
                'advanced_analytics' => 0,
            ],
            [
                'name' => 'العضوية الشهرية المتقدمة',
                'description' => 'عضوية شهرية مع مزايا متقدمة',
                'price' => 400,
                'duration_days' => 30,
                'is_active' => 1,
                'benefits' => json_encode(['حجز قاعات', 'خدمات متقدمة']),
                'max_halls' => 2,
                'max_bookings_per_month' => 6,
                'priority_support' => 1,
                'custom_branding' => 0,
                'advanced_analytics' => 0,
            ],
            [
                'name' => 'العضوية الشهرية الفاخرة',
                'description' => 'عضوية شهرية فاخرة',
                'price' => 800,
                'duration_days' => 30,
                'is_active' => 1,
                'benefits' => json_encode(['حجز قاعات', 'جميع الخدمات']),
                'max_halls' => 3,
                'max_bookings_per_month' => 12,
                'priority_support' => 1,
                'custom_branding' => 1,
                'advanced_analytics' => 1,
            ],
            [
                'name' => 'العضوية الشهرية VIP',
                'description' => 'عضوية شهرية VIP',
                'price' => 2000,
                'duration_days' => 30,
                'is_active' => 1,
                'benefits' => json_encode(['حجز قاعات', 'خدمات VIP']),
                'max_halls' => 5,
                'max_bookings_per_month' => 30,
                'priority_support' => 1,
                'custom_branding' => 1,
                'advanced_analytics' => 1,
            ],
            [
                'name' => 'العضوية ربع السنوية البرونزية',
                'description' => 'عضوية ربع سنوية أساسية',
                'price' => 1200,
                'duration_days' => 90,
                'is_active' => 1,
                'benefits' => json_encode(['حجز قاعات', 'خدمات أساسية']),
                'max_halls' => 1,
                'max_bookings_per_month' => 15,
                'priority_support' => 0,
                'custom_branding' => 0,
                'advanced_analytics' => 0,
            ],
            [
                'name' => 'العضوية ربع السنوية الفضية',
                'description' => 'عضوية ربع سنوية متوسطة',
                'price' => 2400,
                'duration_days' => 90,
                'is_active' => 1,
                'benefits' => json_encode(['حجز قاعات', 'خدمات متقدمة']),
                'max_halls' => 2,
                'max_bookings_per_month' => 30,
                'priority_support' => 1,
                'custom_branding' => 0,
                'advanced_analytics' => 1,
            ],
            [
                'name' => 'العضوية ربع السنوية الذهبية',
                'description' => 'عضوية ربع سنوية فاخرة',
                'price' => 4800,
                'duration_days' => 90,
                'is_active' => 1,
                'benefits' => json_encode(['حجز قاعات', 'جميع الخدمات']),
                'max_halls' => 5,
                'max_bookings_per_month' => 60,
                'priority_support' => 1,
                'custom_branding' => 1,
                'advanced_analytics' => 1,
            ],
            [
                'name' => 'العضوية ربع السنوية البلاتينية',
                'description' => 'عضوية ربع سنوية VIP',
                'price' => 12000,
                'duration_days' => 90,
                'is_active' => 1,
                'benefits' => json_encode(['حجز قاعات', 'خدمات VIP']),
                'max_halls' => 10,
                'max_bookings_per_month' => 150,
                'priority_support' => 1,
                'custom_branding' => 1,
                'advanced_analytics' => 1,
            ],
            [
                'name' => 'العضوية نصف السنوية البرونزية',
                'description' => 'عضوية نصف سنوية أساسية',
                'price' => 2200,
                'duration_days' => 180,
                'is_active' => 1,
                'benefits' => json_encode(['حجز قاعات', 'خدمات أساسية']),
                'max_halls' => 1,
                'max_bookings_per_month' => 30,
                'priority_support' => 0,
                'custom_branding' => 0,
                'advanced_analytics' => 0,
            ],
            [
                'name' => 'العضوية نصف السنوية الفضية',
                'description' => 'عضوية نصف سنوية متوسطة',
                'price' => 4400,
                'duration_days' => 180,
                'is_active' => 1,
                'benefits' => json_encode(['حجز قاعات', 'خدمات متقدمة']),
                'max_halls' => 3,
                'max_bookings_per_month' => 60,
                'priority_support' => 1,
                'custom_branding' => 0,
                'advanced_analytics' => 1,
            ],
            [
                'name' => 'العضوية نصف السنوية الذهبية',
                'description' => 'عضوية نصف سنوية فاخرة',
                'price' => 8800,
                'duration_days' => 180,
                'is_active' => 1,
                'benefits' => json_encode(['حجز قاعات', 'جميع الخدمات']),
                'max_halls' => 5,
                'max_bookings_per_month' => 120,
                'priority_support' => 1,
                'custom_branding' => 1,
                'advanced_analytics' => 1,
            ],
            [
                'name' => 'العضوية نصف السنوية البلاتينية',
                'description' => 'عضوية نصف سنوية VIP',
                'price' => 22000,
                'duration_days' => 180,
                'is_active' => 1,
                'benefits' => json_encode(['حجز قاعات', 'خدمات VIP']),
                'max_halls' => 15,
                'max_bookings_per_month' => 300,
                'priority_support' => 1,
                'custom_branding' => 1,
                'advanced_analytics' => 1,
            ],
        ];

        foreach ($memberships as $membership) {
            DB::table('memberships')->insert(array_merge($membership, [
                'created_at' => now(),
                'updated_at' => now(),
            ]));
        }
    }
}
